### ISSUE TITLE
adapter doesn't start (iLO5)

### ISSUE THREAD

**Issue by Qlink84** [SebastianSchultz/ioBroker.hp-ilo#18]
hi, are there any prerequisites to get the adapter running ?
i want the data from my DL380 Gen10 (iLO5) in iobroker, but the adapter light stays red and i get the following error:

```
host.iobroker | 2020-07-18 21:59:13.199 | info | Restart adapter system.adapter.hp-ilo.0 because enabled
-- | -- | -- | --
host.iobroker | 2020-07-18 21:59:13.199 | error | instance system.adapter.hp-ilo.0 terminated with code 0 (OK)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at endReadableNT (_stream_readable.js:1125:12)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at IncomingMessage.emit (events.js:194:15)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at Request.emit (events.js:189:13)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at Request.<anonymous> (C:\ioBroker\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at Request.callback (C:\ioBroker\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: at C:\ioBroker\node_modules\iobroker.hp-ilo\hp-ilo.js:75:58
Caught | 2020-07-18 21:59:13.199 | error | by controller[0]: TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at endReadableNT (_stream_readable.js:1125:12)
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at IncomingMessage.emit (events.js:194:15)
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at IncomingMessage.<anonymous> (C:\ioBroker\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at Request.emit (events.js:189:13)
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at Request.<anonymous> (C:\ioBroker\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at Request.callback (C:\ioBroker\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | at C:\ioBroker\node_modules\iobroker.hp-ilo\hp-ilo.js:75:58
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2020-07-18 21:59:13.167 | error | uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2020-07-18 21:59:12.824 | info | Ready. Configured HP ILO: 192.168.222.2
```

Node.js: 10.15.3
NPM: 6.9.0
js-controller: 1.5.14
Platform: Windows
ilo-Adapter: 1.0.6

**Comment by SebastianSchultz** [comment]
Hello,

the adapter ist tested only with ILO4. I don't know if it works with ILO5, because I have no system to test it :(

**Comment by Qlink84** [comment]
Hi,
any chances we make it working on iLO5 also ? if i can help you in any way, i'll try to do so...
any special settings that need to be turned on/off:

here are the default access settings of iLO5:
![image](https://user-images.githubusercontent.com/15886027/88509142-b97fb600-cfe0-11ea-82c0-1bcf2e8bbd2a.png)

best regards

**Comment by SebastianSchultz** [comment]
Have you tried to access ILO5 with the adapter?
Are there any error messages?
Sorry I didn't have ILO5 to test it.

**Comment by Qlink84** [comment]
yes, adapter light stays red and log shows following output:


```
hp-ilo.0 | 2020-09-27 08:51:34.708 | info | (6276) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
hp-ilo.0 | 2020-09-27 08:51:34.708 | info | (6276) terminating
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at TLSSocket.emit (events.js:203:15)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at TLSSocket.socketCloseListener (_http_client.js:356:11)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:251:60)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:118:52
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | (6276) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | (6276) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at endReadableNT (_stream_readable.js:1143:12)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:75:58
hp-ilo.0 | 2020-09-27 08:51:34.708 | error | (6276) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2020-09-27 08:51:34.693 | error | (6276) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2020-09-27 08:51:34.396 | info | (6276) Ready. Configured HP ILO: 192.168.222.2
hp-ilo.0 | 2020-09-27 08:51:34.380 | info | (6276) starting. Version 1.0.6 in C:/iobroker/iob01/node_modules/iobroker.hp-ilo, node: v10.17.0, js-controller: 3.1.6
hp-ilo.0 | 2020-09-27 08:51:34.271 | debug | (6276) statesDB connected
hp-ilo.0 | 2020-09-27 08:51:34.271 | debug | (6276) States connected to redis: 127.0.0.1:9000
hp-ilo.0 | 2020-09-27 08:51:34.255 | debug | (6276) States create System PubSub Client
hp-ilo.0 | 2020-09-27 08:51:34.255 | debug | (6276) States create User PubSub Client
hp-ilo.0 | 2020-09-27 08:51:34.255 | debug | (6276) Redis States: Use Redis connection: 127.0.0.1:9000
hp-ilo.0 | 2020-09-27 08:51:34.255 | debug | (6276) objectDB connected
hp-ilo.0 | 2020-09-27 08:51:34.239 | debug | (6276) Objects connected to redis: 127.0.0.1:9001
hp-ilo.0 | 2020-09-27 08:51:34.224 | debug | (6276) Objects client initialize lua scripts
hp-ilo.0 | 2020-09-27 08:51:34.224 | debug | (6276) Objects create User PubSub Client
hp-ilo.0 | 2020-09-27 08:51:34.224 | debug | (6276) Objects create System PubSub Client
hp-ilo.0 | 2020-09-27 08:51:34.224 | debug | (6276) Objects client ready ... initialize now
hp-ilo.0 | 2020-09-27 08:51:34.208 | debug | (6276) Redis Objects: Use Redis connection: 127.0.0.1:9001


```

**Comment by SebastianSchultz** [comment]
The error message says it has problems to identify the fan names.
Does your fans have anyspecial characters in their names?

**Comment by Qlink84** [comment]
not really, they are all default... maybe the space between "Fan" and the number ...?
![image](https://user-images.githubusercontent.com/15886027/94461688-bf4d6f80-01ba-11eb-956e-038881c7dd3f.png)

**Comment by SebastianSchultz** [comment]
No the space is not the problem.
I think ILO5 doesnt work :(
