### ISSUE TITLE
Make Adapter ilo5 compatible [enhancement]

### ISSUE THREAD

**Issue by Qlink84** [SebastianSchultz/ioBroker.hp-ilo#19]
https://github.com/SebastianSchultz/ioBroker.hp-ilo/issues/18#issuecomment-664140977

**Comment by SebastianSchultz** [comment]
I need help from developers with ILO5.
I have no ILO5 device so I can't develop this enhancement. Sorry (

**Comment by Qlink84** [comment]
Maybe i can help you, if you tell me what exactly you need... I have ILO5 here running 24/7...

**Comment by SebastianSchultz** [comment]
Do you have an ILO5 system which I can access from external?
But please NO production system!

**Comment by Qlink84** [comment]
Access from external through teamviewer in a separate test/dev VM would be possible, but it's a production system... so i do have to join the teamviewer session and be present...
Other way would be you tell me which data/commands etc. you need for adapter enhancement and i'll try to give what you need...

**Comment by SebastianSchultz** [comment]
The problem is for development I need direct access to the ILO interface to readout the HTTP requests.
You can debug the adapter by yourself.
In the lines 72 and 73 is an array. if you could output the content of this array to debug log it would be great.

**Comment by Qlink84** [comment]
Sorry, i'm afraid i don't understand what you mean... can you tell me in which file are the lines 72 and 73 are located and how i can output the content of this array ?

when i start ilo adapter in iobroker all i see in error log are the following lines:
`

hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at TLSSocket.emit (events.js:203:15)
-- | -- | -- | --
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at TLSSocket.socketCloseListener (_http_client.js:356:11)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:251:60)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:118:52
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | (5728) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | (5728) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at endReadableNT (_stream_readable.js:1143:12)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:75:58
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | (5728) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-01-11 11:31:05.573 | error | (5728) uncaught exception: Cannot read property 'replace' of undefined

`

**Comment by SebastianSchultz** [comment]
In hp-ilo.js before this line

` for (var f in body.Fans) {`

insert the following:

`adapter.log.debug('body.fans');`

and send me the debug log.

**Comment by Qlink84** [comment]
did that.
![image](https://user-images.githubusercontent.com/15886027/104416956-eca90800-5574-11eb-8b90-6d9e94c37bbf.png)

here's log output

```
`2021-01-13 07:45:19.274  - [32minfo[39m: host.iob01 "system.adapter.hp-ilo.0" enabled
2021-01-13 07:45:19.274  - [32minfo[39m: host.iob01 instance system.adapter.hp-ilo.0 started with pid 8852
2021-01-13 07:45:19.883  - [34mdebug[39m: hp-ilo.0 (8852) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-01-13 07:45:19.898  - [34mdebug[39m: hp-ilo.0 (8852) Objects client ready ... initialize now
2021-01-13 07:45:19.914  - [34mdebug[39m: hp-ilo.0 (8852) Objects create System PubSub Client
2021-01-13 07:45:19.914  - [34mdebug[39m: hp-ilo.0 (8852) Objects create User PubSub Client
2021-01-13 07:45:19.914  - [34mdebug[39m: hp-ilo.0 (8852) Objects client initialize lua scripts
2021-01-13 07:45:19.914  - [34mdebug[39m: hp-ilo.0 (8852) Objects connected to redis: 127.0.0.1:9001
2021-01-13 07:45:19.929  - [34mdebug[39m: hp-ilo.0 (8852) objectDB connected
2021-01-13 07:45:19.929  - [34mdebug[39m: hp-ilo.0 (8852) Redis States: Use Redis connection: 127.0.0.1:9000
2021-01-13 07:45:19.929  - [34mdebug[39m: hp-ilo.0 (8852) States create User PubSub Client
2021-01-13 07:45:19.929  - [34mdebug[39m: hp-ilo.0 (8852) States create System PubSub Client
2021-01-13 07:45:19.945  - [34mdebug[39m: hp-ilo.0 (8852) States connected to redis: 127.0.0.1:9000
2021-01-13 07:45:19.945  - [34mdebug[39m: hp-ilo.0 (8852) statesDB connected
2021-01-13 07:45:20.055  - [32minfo[39m: hp-ilo.0 (8852) starting. Version 1.0.6 in C:/iobroker/iob01/node_modules/iobroker.hp-ilo, node: v10.17.0, js-controller: 3.1.6
2021-01-13 07:45:20.055  - [32minfo[39m: hp-ilo.0 (8852) Ready. Configured HP ILO: 192.168.222.2
2021-01-13 07:45:20.086  - [35msilly[39m: hp-ilo.0 (8852) States system redis pmessage system.adapter.hp-ilo.0.logLevel/system.adapter.hp-ilo.0.logLevel:{"val":"silly","ack":true,"ts":1610520320086,"q":0,"from":"system.adapter.hp-ilo.0","lc":1610361060568}
2021-01-13 07:45:20.367  - [34mdebug[39m: hp-ilo.0 (8852) body.fans
2021-01-13 07:45:20.367  - [31merror[39m: hp-ilo.0 (8852) uncaught exception: Cannot read property 'replace' of undefined
2021-01-13 07:45:20.367  - [31merror[39m: hp-ilo.0 (8852) TypeError: Cannot read property 'replace' of undefined
    at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:76:58
    at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
    at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2021-01-13 07:45:20.383  - [31merror[39m: hp-ilo.0 (8852) uncaught exception: Cannot read property 'replace' of undefined
2021-01-13 07:45:20.383  - [31merror[39m: hp-ilo.0 (8852) TypeError: Cannot read property 'replace' of undefined
    at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:119:52
    at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
    at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:251:60)
    at IncomingMessage.emit (events.js:203:15)
    at TLSSocket.socketCloseListener (_http_client.js:356:11)
    at TLSSocket.emit (events.js:203:15)
2021-01-13 07:45:20.383  - [32minfo[39m: hp-ilo.0 (8852) terminating
2021-01-13 07:45:20.383  - [32minfo[39m: hp-ilo.0 (8852) Terminated (NO_ERROR): Without reason
2021-01-13 07:45:20.900  - [32minfo[39m: host.iob01 instance system.adapter.hp-ilo.0 terminated with code 0 (NO_ERROR)
2021-01-13 07:45:20.900  - [32minfo[39m: host.iob01 Restart adapter system.adapter.hp-ilo.0 because enabled
2021-01-13 07:45:30.827  - [32minfo[39m: host.iob01 "system.adapter.hp-ilo.0" disabled
2021-01-13 07:45:51.427  - [34mdebug[39m: hp-ilo.0 (7632) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-01-13 07:45:51.443  - [34mdebug[39m: hp-ilo.0 (7632) Objects client ready ... initialize now
2021-01-13 07:45:51.443  - [34mdebug[39m: hp-ilo.0 (7632) Objects create System PubSub Client
2021-01-13 07:45:51.443  - [34mdebug[39m: hp-ilo.0 (7632) Objects create User PubSub Client
2021-01-13 07:45:51.443  - [34mdebug[39m: hp-ilo.0 (7632) Objects client initialize lua scripts
2021-01-13 07:45:51.458  - [34mdebug[39m: hp-ilo.0 (7632) Objects connected to redis: 127.0.0.1:9001
2021-01-13 07:45:51.458  - [34mdebug[39m: hp-ilo.0 (7632) objectDB connected
2021-01-13 07:45:51.458  - [34mdebug[39m: hp-ilo.0 (7632) Redis States: Use Redis connection: 127.0.0.1:9000
2021-01-13 07:45:51.474  - [34mdebug[39m: hp-ilo.0 (7632) States create User PubSub Client
2021-01-13 07:45:51.474  - [34mdebug[39m: hp-ilo.0 (7632) States create System PubSub Client
2021-01-13 07:45:51.474  - [34mdebug[39m: hp-ilo.0 (7632) States connected to redis: 127.0.0.1:9000
2021-01-13 07:45:51.474  - [34mdebug[39m: hp-ilo.0 (7632) statesDB connected
2021-01-13 07:45:51.599  - [31merror[39m: hp-ilo.0 (7632) adapter disabled
2021-01-13 07:45:51.614  - [33mwarn[39m: hp-ilo.0 (7632) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason`
```

**Comment by SebastianSchultz** [comment]
can you please uncomment the lines 72 to 84 with // ?
It seems that the resoond does not include the fan information.

**Comment by Qlink84** [comment]
i've uncommented the lines as described:
![image](https://user-images.githubusercontent.com/15886027/111176284-7c852580-85a9-11eb-8581-ad6d8d5c8f37.png)

Here is iobroker log output:

```

host.iob01 | 2021-03-15 16:14:10.519 | info | Restart adapter system.adapter.hp-ilo.0 because enabled
-- | -- | -- | --
host.iob01 | 2021-03-15 16:14:10.519 | error | instance system.adapter.hp-ilo.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[3]: at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[3]: bootstrap/node.js:283:19)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[2]: at startup (internal/
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[2]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[2]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[2]: modules/cjs/loader.js:593:12)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: at tryModuleLoad (internal/
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: at Module._compile (internal/modules/cjs/loader.js:723:23)
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: SyntaxError: missing ) after argument list
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]:
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: ^
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: }
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[1]: es\iobroker.hp-ilo\hp-ilo.js:114
host.iob01 | 2021-03-15 16:14:10.519 | error | Caught by controller[0]: C:\iobroker\iob01\node_modul
host.iob01 | 2021-03-15 16:14:10.378 | info | instance system.adapter.hp-ilo.0 started with pid 8440
```

**Comment by SebastianSchultz** [comment]
I'm sorry, please uncomment also line 85.
My fault :)

**Comment by Qlink84** [comment]
okay, did that as well.

here's log output

```

hp-ilo.0 | 2021-03-15 16:42:28.082 | info | (6016) terminating
-- | -- | -- | --
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at TLSSocket.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at TLSSocket.socketCloseListener (_http_client.js:356:11)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:251:60)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:119:52
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | (6016) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 16:42:28.082 | error | (6016) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at endReadableNT (_stream_readable.js:1143:12)
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:119:52
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | (6016) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 16:42:28.066 | error | (6016) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 16:42:27.753 | silly | (6016) States system redis pmessage system.adapter.hp-ilo.0.logLevel/system.adapter.hp-ilo.0.logLevel:{"val":"silly","ack":true,"ts":1615822947738,"q":0,"from":"system.adapter.hp-ilo.0","lc":16103610
hp-ilo.0 | 2021-03-15 16:42:27.722 | info | (6016) Ready. Configured HP ILO: 192.168.222.2
hp-ilo.0 | 2021-03-15 16:42:27.706 | info | (6016) starting. Version 1.0.6 in C:/iobroker/iob01/node_modules/iobroker.hp-ilo, node: v10.17.0, js-controller: 3.1.6
hp-ilo.0 | 2021-03-15 16:42:27.613 | debug | (6016) statesDB connected
hp-ilo.0 | 2021-03-15 16:42:27.613 | debug | (6016) States connected to redis: 127.0.0.1:9000
hp-ilo.0 | 2021-03-15 16:42:27.597 | debug | (6016) States create System PubSub Client
hp-ilo.0 | 2021-03-15 16:42:27.597 | debug | (6016) States create User PubSub Client
hp-ilo.0 | 2021-03-15 16:42:27.597 | debug | (6016) Redis States: Use Redis connection: 127.0.0.1:9000
hp-ilo.0 | 2021-03-15 16:42:27.597 | debug | (6016) objectDB connected
hp-ilo.0 | 2021-03-15 16:42:27.582 | debug | (6016) Objects connected to redis: 127.0.0.1:9001
hp-ilo.0 | 2021-03-15 16:42:27.582 | debug | (6016) Objects client initialize lua scripts
hp-ilo.0 | 2021-03-15 16:42:27.582 | debug | (6016) Objects create User PubSub Client
hp-ilo.0 | 2021-03-15 16:42:27.582 | debug | (6016) Objects create System PubSub Client
hp-ilo.0 | 2021-03-15 16:42:27.582 | debug | (6016) Objects client ready ... initialize now
hp-ilo.0 | 2021-03-15 16:42:27.550 | debug | (6016) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.iob01 | 2021-03-15 16:42:27.049 | info | instance system.adapter.hp-ilo.0 started with pid 6016
host.iob01 | 2021-03-15 16:42:27.049 | info | "system.adapter.hp-ilo.0" enabled
```

**Comment by SebastianSchultz** [comment]
I'm sorry, but with this adapter we didn't get any respond from ILO5 :(

**Comment by Qlink84** [comment]
:(

**Comment by SebastianSchultz** [comment]
Can you please replce the hp-ilo.js file with the attached?
Please enable debug log, start the adapter and post the log output so we can see if there is any response from ILO5.
[hp-ilo.zip](https://github.com/SebastianSchultz/ioBroker.hp-ilo/files/6142986/hp-ilo.zip)

**Comment by Qlink84** [comment]
here you are:


```
host.iob01 | 2021-03-15 17:45:43.627 | info | Restart adapter system.adapter.hp-ilo.0 because enabled
-- | -- | -- | --
host.iob01 | 2021-03-15 17:45:43.627 | error | instance system.adapter.hp-ilo.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at startup (internal/bootstrap/node.js:283:19)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:723:23)
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: SyntaxError: Unexpected token ,
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]:
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: ^
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: }, !true);
host.iob01 | 2021-03-15 17:45:43.627 | error | Caught by controller[0]: C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:68
host.iob01 | 2021-03-15 17:45:43.440 | info | instance system.adapter.hp-ilo.0 started with pid 8980
host.iob01 | 2021-03-15 17:45:43.409 | info | "system.adapter.hp-ilo.0" enabled


```

**Comment by Qlink84** [comment]
maybe this helps ? https://github.com/HewlettPackard/ilo-rest-api-docs/blob/master/source/includes/_ilo5_introduction.md

**Comment by SebastianSchultz** [comment]
[hp-ilo.zip](https://github.com/SebastianSchultz/ioBroker.hp-ilo/files/6143279/hp-ilo.zip)

You can try this new attached .js file. But it seems that HP changed the authentication mechanism :(

**Comment by Qlink84** [comment]
Windows Defender Alert with this file -.-
![image](https://user-images.githubusercontent.com/15886027/111200477-18bb2680-85c2-11eb-84c1-657a2b670f23.png)

**Comment by SebastianSchultz** [comment]
Hmm its the same .js only with other URIs...

**Comment by Qlink84** [comment]
```

host.iob01 | 2021-03-15 20:07:08.380 | info | Restart adapter system.adapter.hp-ilo.0 because enabled
-- | -- | -- | --
host.iob01 | 2021-03-15 20:07:08.379 | info | instance system.adapter.hp-ilo.0 terminated with code 0 (NO_ERROR)
hp-ilo.0 | 2021-03-15 20:07:07.843 | info | (5632) Terminated (NO_ERROR): Without reason
hp-ilo.0 | 2021-03-15 20:07:07.843 | info | (5632) terminating
hp-ilo.0 | 2021-03-15 20:07:07.842 | error | (5632) TypeError: Cannot read property 'replace' of undefined at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:120:52 at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp
hp-ilo.0 | 2021-03-15 20:07:07.842 | error | (5632) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 20:07:07.837 | error | (5632) TypeError: Cannot read property 'replace' of undefined at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:77:58 at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-
hp-ilo.0 | 2021-03-15 20:07:07.837 | error | (5632) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 20:07:07.836 | debug | (5632) Body Response JSON: {"@odata.context":"/redfish/v1/$metadata#Thermal.Thermal","@odata.etag":"W/\"285DD7EE\"","@odata.id":"/redfish/v1/Chassis/1/Thermal","@odata.type":"#Thermal.v1_1_0.Thermal",
hp-ilo.0 | 2021-03-15 20:07:07.836 | debug | (5632) Body Response raw: [object Object]
hp-ilo.0 | 2021-03-15 20:07:07.582 | silly | (5632) States system redis pmessage system.adapter.hp-ilo.0.logLevel/system.adapter.hp-ilo.0.logLevel:{"val":"silly","ack":true,"ts":1615835227578,"q":0,"from":"system.adapter.hp-ilo.0","lc":161036106
hp-ilo.0 | 2021-03-15 20:07:07.547 | info | (5632) Ready. Configured HP ILO: 192.168.222.2
hp-ilo.0 | 2021-03-15 20:07:07.539 | info | (5632) starting. Version 1.0.6 in C:/iobroker/iob01/node_modules/iobroker.hp-ilo, node: v10.17.0, js-controller: 3.1.6
host.iob01 | 2021-03-15 20:07:06.711 | info | instance system.adapter.hp-ilo.0 started with pid 5632
host.iob01 | 2021-03-15 20:06:36.704 | info | Restart adapter system.adapter.hp-ilo.0 because enabled
host.iob01 | 2021-03-15 20:06:36.703 | info | instance system.adapter.hp-ilo.0 terminated with code 0 (NO_ERROR)
hp-ilo.0 | 2021-03-15 20:06:36.170 | info | (9056) Terminated (NO_ERROR): Without reason
hp-ilo.0 | 2021-03-15 20:06:36.170 | info | (9056) terminating
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at TLSSocket.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at TLSSocket.socketCloseListener (_http_client.js:356:11)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:251:60)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:120:52
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | (9056) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 20:06:36.169 | error | (9056) uncaught exception: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at endReadableNT (_stream_readable.js:1143:12)
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at IncomingMessage.emit (events.js:203:15)
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at IncomingMessage.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:278:54)
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at Request.emit (events.js:198:13)
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at Request.<anonymous> (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\node_modules\request\main.js:290:21)
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at Request.callback (C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:52:3)
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | at C:\iobroker\iob01\node_modules\iobroker.hp-ilo\hp-ilo.js:77:58
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | (9056) TypeError: Cannot read property 'replace' of undefined
hp-ilo.0 | 2021-03-15 20:06:36.164 | error | (9056) uncaught exception: Cannot read property 'replace' of undefined


```

**Comment by SebastianSchultz** [comment]
Sorry this needs further investigation...
