### ISSUE TITLE
Error since js-controller Update 3.3.8

### ISSUE THREAD

**Issue by Kufstein** [SebastianSchultz/ioBroker.hp-ilo#24]
Hi, 

I have Errors in this Adapter since I update the js-controller to version 3.3.8:

`hp-ilo.0	2021-05-05 17:18:57.673	error	(62741) The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.673	error	(62741) Error: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada
hp-ilo.0	2021-05-05 17:18:57.672	error	(62741) unhandled promise rejection: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.672	error	(62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hp-ilo.0	2021-05-05 17:18:57.671	error	(62741) The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.671	error	(62741) Error: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada
hp-ilo.0	2021-05-05 17:18:57.670	error	(62741) unhandled promise rejection: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.670	error	(62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hp-ilo.0	2021-05-05 17:18:57.669	error	(62741) The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.669	error	(62741) Error: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada
hp-ilo.0	2021-05-05 17:18:57.668	error	(62741) unhandled promise rejection: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.668	error	(62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hp-ilo.0	2021-05-05 17:18:57.636	error	(62741) The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.636	error	(62741) Error: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada
hp-ilo.0	2021-05-05 17:18:57.635	error	(62741) unhandled promise rejection: The id "temperatures.33-PCI_3_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.634	error	(62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hp-ilo.0	2021-05-05 17:18:57.634	error	(62741) The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.633	error	(62741) Error: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada
hp-ilo.0	2021-05-05 17:18:57.633	error	(62741) unhandled promise rejection: The id "temperatures.32-PCI_2_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.632	error	(62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hp-ilo.0	2021-05-05 17:18:57.630	error	(62741) The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.630	error	(62741) Error: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Ada
hp-ilo.0	2021-05-05 17:18:57.627	error	(62741) unhandled promise rejection: The id "temperatures.31-PCI_1_Zone." is invalid. Ids are not allowed to end in "."
hp-ilo.0	2021-05-05 17:18:57.626	error	(62741) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
`

I have try to uninstall and reinstall the ilo-adapter, but no luck.

**Comment by SebastianSchultz** [comment]
Can you create this issue in the js-controller repository?

**Comment by SebastianSchultz** [comment]
Do you have dots in your Fan Name?

`The id "temperatures.33-PCI_3_Zone." is invalid.`

I've tested the adapter with my ILO interface but I only have one fan named "Fan 1". That works without any errors.

**Comment by Apollon77** [comment]
@SebastianSchultz This is no js.controller issue ... State ids with a "pint" at the end are invalid since js.controller 3 and enforced since 3.2 already ... So the adapter should make sure such state ids are not generated

**Comment by Kufstein** [comment]
> Do you have dots in your Fan Name?
> 
> `The id "temperatures.33-PCI_3_Zone." is invalid.`
> 
> I've tested the adapter with my ILO interface but I only have one fan named "Fan 1". That works without any errors.

not really. I can't set a name in ILO for the fan. The Server is a HP ProLiant DL380Gen9 with ILO 4 version 2.75 Aug 13 2020.
In the ILO i see only : Fan 1, Fan 2, Fan 3, Fan 4, Fan5 and Fan6

**Comment by SebastianSchultz** [comment]
> 
> 
> @SebastianSchultz This is no js.controller issue ... State ids with a "pint" at the end are invalid since js.controller 3 and enforced since 3.2 already ... So the adapter should make sure such state ids are not generated

Hello Ingo,

can you see in the code where this happens? For me it works :(

**Comment by Apollon77** [comment]
Honestly. Add a debug log for the data you process and get from the ILO and ask user to provide log, then you should see it better
